routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::get('products/{id}/rates/', 'RateController@index')->name('rate.index');
Route::get('products/{id}/rates/create', 'RateController@create')->name('rate.create');
Route::post('products/{id}/rates', 'RateController@store')->name('rate.store');
Route::get('products/{id}/rates/{rateId}', 'RateController@show')->name('rate.show');
Route::get('products/{id}/rates/{rateId}/edit', 'RateController@edit')->name('rate.edit');
Route::patch('products/{id}/rates/{rateId}', 'RateController@update')->name('rate.update');
Route::delete('products/{id}/rates/{rateId}', 'RateController@destroy')->name('rate.destroy');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ["id"];
    protected $table = "categories";

    protected $fillable = [
        'code',
        'name',
        'description',
        'active'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'updated_at'
    ];

    public function scopeId($query, $request)
    {
        if($request->has('id')){
            $query->where('id', $request->id);
        }
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Core\Categories\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $core = new Category(new Request());
        $list = $core->show()->get();
        return view('categories.list', compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $core = new Category($request);
        $core->create();
        return redirect('/categories')->with('success', 'Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $core = new Category(new Request([
            "id" => $id
        ]));
        $category = $core->show()->first();
        return view('categories.view', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $core = new Category(new Request([
            "id" => $id
        ]));
        $category = $core->show()->first();
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $core = new Category($request);
        $core->edit($id);
        return redirect('/categories')->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $core = new Category();
        $core->delete($id);
        return redirect('/categories')->with('success', 'Category deleted successfully');
    }
}

resources/views/categories/create.blade.php
@extends('welcome')
@section('content')
    <div class="row">
        <div class="col-lg-11">
            <h2>Add New Categories</h2>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('categories') }}"> Back</a>
        </div>
    </div>
 
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('categories.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="txtFirstName">Code:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Category code" name="code">
        </div>
        <div class="form-group">
            <label for="txtFirstName">Name:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Category Name" name="name">
        </div>
        <div class="form-group">
            <label for="txtDescription">Description:</label>
            <textarea class="form-control" id="txtDescription" name="description" rows="10" placeholder="Description"></textarea>
        </div>
        <button type="submit" class="btn btn-default">Save</button>
    </form>
@endsection

resources/views/categories/edit.blade.php
@extends('welcome')
@section('content')
    <div class="row">
        <div class="col-lg-11">
            <h2>Update Category</h2>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('categories') }}"> Back</a>
        </div>
    </div>
 
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('categories.update',$category->id) }}" >
        @method('PATCH')
        @csrf

        <div class="form-group">
            <label for="txtFirstName">Code:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Product code" name="code" value="{{ $category->code }}">
        </div>
        <div class="form-group">
            <label for="txtFirstName">Name:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Enter Name" name="name" value="{{ $category->name }}">
        </div>
        <div class="form-group">
            <label for="txtDescription">Description:</label>
            <textarea class="form-control" id="txtDescription" name="description" rows="10" placeholder="Enter Address"> {{$category->description}} </textarea>
        </div>
        <button type="submit" class="btn btn-default">Save</button>
    </form>
@endsection

resources/views/categories/list.blade.php
@extends('welcome')
@section('content')

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Categories</h6>

        <div class="col-lg-1">
            <a class="btn btn-success" href="{{ route('categories.create') }}">Add</a>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <th>code</th>
                    <th>name</th>
                    <th>description</th>
                    <th>active</th>
                    <th width="280px">Action</th>
                </tr>
                @foreach ($list as $item)
                <tr>
                    <td>{{ $item->code }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->description }}</td>
                    <td>{{ $item->active }}</td>
                    <td>
                        <form action="{{ route('categories.destroy',$item->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('categories.show',$item->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('categories.edit',$item->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>

@endsection

resources/views/categories/view.blade.php
@extends('welcome')
@section('content')
    <div class="row">
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('categories') }}"> Back</a>
        </div>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>Code:</th>
            <td>{{ $category->code }}</td>
        </tr>
        <tr>
            <th>Name:</th>
            <td>{{ $category->name }}</td>
        </tr>
        <tr>
            <th>Address:</th>
            <td>{{ $category->description }}</td>
        </tr>
 
    </table>
@endsection