routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::get('products/{id}/rates/', 'RateController@index')->name('rate.index');
Route::get('products/{id}/rates/create', 'RateController@create')->name('rate.create');
Route::post('products/{id}/rates', 'RateController@store')->name('rate.store');
Route::get('products/{id}/rates/{rateId}', 'RateController@show')->name('rate.show');
Route::get('products/{id}/rates/{rateId}/edit', 'RateController@edit')->name('rate.edit');
Route::patch('products/{id}/rates/{rateId}', 'RateController@update')->name('rate.update');
Route::delete('products/{id}/rates/{rateId}', 'RateController@destroy')->name('rate.destroy');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ["id"];
    protected $table = "products";

    protected $fillable = [
        'code',
        'name',
        'description',
        'active'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'updated_at'
    ];

    public function categories()
    {
        return $this->belongsToMany("App\Models\Category", "product_categories", "product_id", "category_id");
    }

    public function scopeId($query, $request)
    {
        if($request->has('id')){
            $query->where('id', $request->id);
        }
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Core\Products\Product;
use App\Models\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
       /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $core = new Product(new Request());
        $list= $core->show()->get();
        return view('products.list', compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('active',true)->get();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $core = new Product($request);
        $core->create();
        return redirect('/products')->with('success', 'Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $core = new Product(new Request([
            "id"=>$id
        ]));
        $product= $core->show()
            ->first()
            ->load(["categories"]);
        return view('products.view', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $core = new Product(new Request([
            "id"=>$id
        ]));
        $product= $core->show()
            ->first()
            ->load(["categories"]);

        $categories = Category::where('active',true)->get();
        return view('products.edit', compact('product','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $core = new Product($request);
        $core->edit($id);
        return redirect('/products')->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $core = new Product();
        $core->delete($id);
        return redirect('/products')->with('success', 'Category deleted successfully');
    }
}

resources/views/products/create.blade.php
@extends('welcome')
@section('content')
    <div class="row">
        <div class="col-lg-11">
            <h2>Add New Product</h2>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('products') }}"> Back</a>
        </div>
    </div>
 
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('products.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="txtFirstName">Code:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Product code" name="code">
        </div>
        <div class="form-group">
            <label for="txtFirstName">Name:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Product Name" name="name">
        </div>
        <div class="form-group">
            <label for="txtDescription">Description:</label>
            <textarea class="form-control" id="txtDescription" name="description" rows="10" placeholder="Description"></textarea>
        </div>
        <div class="form-group">
            <label for="txtDescription">Categories:</label>
            <select class="form-control" id="txtCategories" name="categories[]" multiple>
            @foreach ($categories as $category)
                <option value="{{$category->id}}"> {{$category->name}} </option>
            @endforeach                
            </select>
        </div>
        <button type="submit" class="btn btn-default">Save</button>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('welcome')
@section('content')
    <div class="row">
        <div class="col-lg-11">
            <h2>Update Category</h2>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('products') }}"> Back</a>
        </div>
    </div>
 
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('products.update',$product->id) }}" >
        @method('PATCH')
        @csrf

        <div class="form-group">
            <label for="txtFirstName">Code:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Product code" name="code" value="{{ $product->code }}">
        </div>
        <div class="form-group">
            <label for="txtFirstName">Name:</label>
            <input type="text" class="form-control" id="txtFirstName" placeholder="Product Name" name="name" value="{{ $product->name }}">
        </div>
        <div class="form-group">
            <label for="txtDescription">Description:</label>
            <textarea class="form-control" id="txtDescription" name="description" rows="10" placeholder="Description"> {{$product->description}} </textarea>
        </div>
        <div class="form-group">
            <label for="txtDescription">Categories:</label>
            <select class="form-control" id="txtCategories" name="categories[]" multiple>
            @foreach ($categories as $category)
            <option value="{{$category->id}}"@if(in_array($category->id, $product->categories->pluck('id')->toArray()))selected="selected"@endif> {{$category->name}} </option>
            @endforeach                
            </select>
        </div>
        <button type="submit" class="btn btn-default">Save</button>
    </form>
@endsection

resources/views/products/list.blade.php
@extends('welcome')
@section('content')

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Products</h6>

        <div class="col-lg-1">
            <a class="btn btn-success" href="{{ route('products.create') }}">Add</a>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered">
        <tr>
            <th>code</th>
            <th>name</th>
            <th>description</th>
            <th>active</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($list as $item)
            <tr>
                <td>{{ $item->code }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->description }}</td>
                <td>{{ $item->active }}</td>
                <td>
                    <form action="{{ route('products.destroy',$item->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('products.show',$item->id) }}">Show</a>
                        <a class="btn btn-primary" href="{{ route('products.edit',$item->id) }}">Edit</a>
                        <a class="btn btn-primary" href="{{ route('rate.index',['id'=>$item->id]) }}">Rates</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
        </div>
    </div>
</div>

@endsection

resources/views/products/view.blade.php
@extends('welcome')
@section('content')
    <div class="row">
        <div class="col-lg-11">
                <h2> Producto {{$product->name}} </h2>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('products') }}"> Back</a>
        </div>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>Code:</th>
            <td>{{ $product->code }}</td>
        </tr>
        <tr>
            <th>Name:</th>
            <td>{{ $product->name }}</td>
        </tr>
        <tr>
            <th>Description:</th>
            <td>{{ $product->description }}</td>
        </tr>
 
    </table>

    <div class="row">
        <div class="col-lg-11">
                <h2> Categories </h2>
        </div>
    </div>

    @foreach ($product->categories as $category)
        <table class="table table-bordered">
            <tr>
                <th>Code:</th>
                <td>{{ $category->code }}</td>
            </tr>
            <tr>
                <th>Name:</th>
                <td>{{ $category->name }}</td>
            </tr>
            <tr>
                <th>Description:</th>
                <td>{{ $category->description }}</td>
            </tr>
        </table>
    @endforeach  
@endsection